# NUMPY


In [21]:
import numpy as np

In [22]:
a1 = np.array([1,2,3,4,5,6])      # 1d array
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])   #2d array
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  #3d array
print(a1)
print("\n")
print(a2)
print("\n")
print(a3)

[1 2 3 4 5 6]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Different ways of initializing array


In [31]:
print(np.ones((3,3)))  #initializing with 1 
print(np.zeros((3,3))) #initializing wiht 0

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
np.random.random((3,3)) #generate a random number between 0 and 1 of given dimension

array([[0.49781901, 0.82644777, 0.4477696 ],
       [0.08167238, 0.42382653, 0.49413025],
       [0.49363472, 0.40135968, 0.53014061]])

In [35]:
np.linspace(-10,10,9)   # generate 9 number between -10 and 10 and each number is in equal distance form other 

array([-10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5,  10. ])

## Array attributes

In [44]:
a1 = np.array([1,2,3,4,5,6])      # 1d array
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])   #2d array
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  #3d array


print(a2.ndim)  # Gives dimension of an array
print(a3.shape) # Gives order of np.array Interpreted as 2 matrix of 2*3 order

print(a2.size)  # Gives total number of items(element)
print(a2.itemsize) #Gives size of each items

2
(2, 2, 3)
12
8


In [49]:
a_f = np.zeros((3,3))
a_f.dtype # gives the datatype of an array

dtype('float64')

## Changing Datatype

In [54]:
a3.astype(np.int32) #change 64-bit datatype into 32-bit datatype

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)

## Array operation

In [56]:
a1 = np.arange (12).reshape (3,4)
a2= np.arange (12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [57]:
# scaler = vector  (some operation) scaler
a1 *2  # to all element of array a1 multiply by 2
a1 +2  # to all element of array a1 add by 2 

a2 == 15  # every place where ther is 15 there will be true 

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [58]:
# vector operation = vector (some operation) vector
a1 + a1

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

## Array Function

In [68]:
a1= np.random.random((3,3))
a1= np.round(a1*100)    # random number between 1 and 100
a1

array([[46., 59.,  3.],
       [ 8., 96., 83.],
       [86., 51., 72.]])

In [71]:
np.max(a2)   # max number from total array
np.max(a2,axis=0) # Max number form each column 0->col and 1->row  


23

In [70]:
np.mean(a2) # give mean or total array

np.median(a2) #give median of an array

np.std(a2,axis=1) # give standard deviation of each row

np.var(a2)   # variance of array

array([1.11803399, 1.11803399, 1.11803399])

In [77]:
# dot product
a2= np.arange(12).reshape(3,4)
a3= np.arange(12,24).reshape(4,3)

np.dot(a2,a3)  # dot product of 2 matrix

#log and exp
np.exp(a2)

# round = "round of to nxt int " and float = "round of to prev int "

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

## Array slicing

In [ ]:
# Creating array
a1 = np.array([1,2,3,4,5,6])      # 1d array
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])   #2d array
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  #3d array
print(a1)
print("\n")
print(a2)
print("\n")
print(a3)

In [16]:
        #selecting specific data 

a2[1, 3]             #first->row , second->column
        # for 3d
a3[1,0,1]            # first->matrix second->row , third->column

8

In [78]:
a2[0,:] #all element of zero row since colunm is not filled selcet all col i.e row

array([0, 1, 2, 3])

In [79]:
a2[:,2]  #all element of col row

array([ 2,  6, 10])

In [ ]:
a2[::2,::3] 